# Generated by Django 4.1.3 on 2023-06-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_icon',
            field=models.ImageField(default='icon.png', upload_to='customers'),
        ),
    ]
